import Head from "next/head";
import Hero from "../components/Hero";
import Navbar from "../components/Navbar";
import FeaturedDresses from "../components/Featured";

export default function Home() {
  return (
    <div>
      <Head>
        <title>StyleThisRentals</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar home={true} />

      <Hero heading="Local Gown Rentals" message="Based in Anchorage, AK" />
      <FeaturedDresses season="Winter" />
    </div>
  );
}
